enum Id {
	UNUSED,
	SURVIVE_1,
	FISH_1,
	SWIM_1,
	WALK_1,
	DODGE_1,
	BULLY_1,
	SURVIVE_2,
	FISH_2,
	SWIM_2,
	WALK_2,
	DODGE_2,
	BULLY_2,
	SURVIVE_3,
	FISH_3,
	SWIM_3,
	WALK_3,
	DODGE_3,
	BULLY_3,
	BUFFET,
	MONA_LISA,
	BULLET_HELL,
}

const Names = {
	Id.SURVIVE_1: "Survive Lv. 1",
	Id.FISH_1: "Eat the Fish Lv. 1",
	Id.SWIM_1: "Go for a Swim Lv. 1",
	Id.WALK_1: "Trace Walking Lv. 1",
	Id.DODGE_1: "Avoid them Lv. 1",
	Id.BULLY_1: "Hit them! Lv. 1",
	Id.SURVIVE_2: "Survive Lv. 2",
	Id.FISH_2: "Eat the Fish Lv. 2",
	Id.SWIM_2: "Go for a Swim Lv. 2",
	Id.WALK_2: "Trace Walking Lv. 2",
	Id.DODGE_2: "Avoid them Lv. 2",
	Id.BULLY_2: "Hit them! Lv. 2",
	Id.SURVIVE_3: "Survive Lv. 3",
	Id.FISH_3: "Eat the Fish Lv. 3",
	Id.SWIM_3: "Go for a Swim Lv. 3",
	Id.WALK_3: "Trace Walking Lv. 3",
	Id.DODGE_3: "Avoid them Lv. 3",
	Id.BULLY_3: "Hit them! Lv. 3",
	Id.BUFFET: "Sp - Free Buffet",
	Id.MONA_LISA: "Sp - Artist",
	Id.BULLET_HELL: "Sp - Bullet Hell",
}
